// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UUID idTask = 1;</code>
   * @return Whether the idTask field is set.
   */
  boolean hasIdTask();
  /**
   * <code>.UUID idTask = 1;</code>
   * @return The idTask.
   */
  grpc.UUID getIdTask();
  /**
   * <code>.UUID idTask = 1;</code>
   */
  grpc.UUIDOrBuilder getIdTaskOrBuilder();
}
