// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public interface BalanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Balance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.BDecimal amount = 1;</code>
   * @return Whether the amount field is set.
   */
  boolean hasAmount();
  /**
   * <code>.BDecimal amount = 1;</code>
   * @return The amount.
   */
  grpc.BDecimal getAmount();
  /**
   * <code>.BDecimal amount = 1;</code>
   */
  grpc.BDecimalOrBuilder getAmountOrBuilder();
}
