// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public interface BDecimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BDecimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 scale = 1;</code>
   * @return The scale.
   */
  int getScale();

  /**
   * <code>.BInteger int_val = 2;</code>
   * @return Whether the intVal field is set.
   */
  boolean hasIntVal();
  /**
   * <code>.BInteger int_val = 2;</code>
   * @return The intVal.
   */
  grpc.BInteger getIntVal();
  /**
   * <code>.BInteger int_val = 2;</code>
   */
  grpc.BIntegerOrBuilder getIntValOrBuilder();
}
