// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public interface BIntegerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BInteger)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes value = 1;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
