// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

/**
 * Protobuf type {@code CashFlow}
 */
public final class CashFlow extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CashFlow)
    CashFlowOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CashFlow.newBuilder() to construct.
  private CashFlow(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CashFlow() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CashFlow();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CashFlow(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            grpc.UUID.Builder subBuilder = null;
            if (userId_ != null) {
              subBuilder = userId_.toBuilder();
            }
            userId_ = input.readMessage(grpc.UUID.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userId_);
              userId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            grpc.BDecimal.Builder subBuilder = null;
            if (amount_ != null) {
              subBuilder = amount_.toBuilder();
            }
            amount_ = input.readMessage(grpc.BDecimal.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(amount_);
              amount_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.Payment.internal_static_CashFlow_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.Payment.internal_static_CashFlow_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.CashFlow.class, grpc.CashFlow.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private grpc.UUID userId_;
  /**
   * <code>.UUID userId = 1;</code>
   * @return Whether the userId field is set.
   */
  @java.lang.Override
  public boolean hasUserId() {
    return userId_ != null;
  }
  /**
   * <code>.UUID userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public grpc.UUID getUserId() {
    return userId_ == null ? grpc.UUID.getDefaultInstance() : userId_;
  }
  /**
   * <code>.UUID userId = 1;</code>
   */
  @java.lang.Override
  public grpc.UUIDOrBuilder getUserIdOrBuilder() {
    return getUserId();
  }

  public static final int AMOUNT_FIELD_NUMBER = 2;
  private grpc.BDecimal amount_;
  /**
   * <code>.BDecimal amount = 2;</code>
   * @return Whether the amount field is set.
   */
  @java.lang.Override
  public boolean hasAmount() {
    return amount_ != null;
  }
  /**
   * <code>.BDecimal amount = 2;</code>
   * @return The amount.
   */
  @java.lang.Override
  public grpc.BDecimal getAmount() {
    return amount_ == null ? grpc.BDecimal.getDefaultInstance() : amount_;
  }
  /**
   * <code>.BDecimal amount = 2;</code>
   */
  @java.lang.Override
  public grpc.BDecimalOrBuilder getAmountOrBuilder() {
    return getAmount();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != null) {
      output.writeMessage(1, getUserId());
    }
    if (amount_ != null) {
      output.writeMessage(2, getAmount());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUserId());
    }
    if (amount_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAmount());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.CashFlow)) {
      return super.equals(obj);
    }
    grpc.CashFlow other = (grpc.CashFlow) obj;

    if (hasUserId() != other.hasUserId()) return false;
    if (hasUserId()) {
      if (!getUserId()
          .equals(other.getUserId())) return false;
    }
    if (hasAmount() != other.hasAmount()) return false;
    if (hasAmount()) {
      if (!getAmount()
          .equals(other.getAmount())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUserId()) {
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
    }
    if (hasAmount()) {
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.CashFlow parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.CashFlow parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.CashFlow parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.CashFlow parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.CashFlow parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.CashFlow parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.CashFlow parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.CashFlow parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.CashFlow parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.CashFlow parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.CashFlow parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.CashFlow parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.CashFlow prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CashFlow}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CashFlow)
      grpc.CashFlowOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Payment.internal_static_CashFlow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Payment.internal_static_CashFlow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.CashFlow.class, grpc.CashFlow.Builder.class);
    }

    // Construct using grpc.CashFlow.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userIdBuilder_ == null) {
        userId_ = null;
      } else {
        userId_ = null;
        userIdBuilder_ = null;
      }
      if (amountBuilder_ == null) {
        amount_ = null;
      } else {
        amount_ = null;
        amountBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.Payment.internal_static_CashFlow_descriptor;
    }

    @java.lang.Override
    public grpc.CashFlow getDefaultInstanceForType() {
      return grpc.CashFlow.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.CashFlow build() {
      grpc.CashFlow result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.CashFlow buildPartial() {
      grpc.CashFlow result = new grpc.CashFlow(this);
      if (userIdBuilder_ == null) {
        result.userId_ = userId_;
      } else {
        result.userId_ = userIdBuilder_.build();
      }
      if (amountBuilder_ == null) {
        result.amount_ = amount_;
      } else {
        result.amount_ = amountBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.CashFlow) {
        return mergeFrom((grpc.CashFlow)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.CashFlow other) {
      if (other == grpc.CashFlow.getDefaultInstance()) return this;
      if (other.hasUserId()) {
        mergeUserId(other.getUserId());
      }
      if (other.hasAmount()) {
        mergeAmount(other.getAmount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.CashFlow parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.CashFlow) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private grpc.UUID userId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.UUID, grpc.UUID.Builder, grpc.UUIDOrBuilder> userIdBuilder_;
    /**
     * <code>.UUID userId = 1;</code>
     * @return Whether the userId field is set.
     */
    public boolean hasUserId() {
      return userIdBuilder_ != null || userId_ != null;
    }
    /**
     * <code>.UUID userId = 1;</code>
     * @return The userId.
     */
    public grpc.UUID getUserId() {
      if (userIdBuilder_ == null) {
        return userId_ == null ? grpc.UUID.getDefaultInstance() : userId_;
      } else {
        return userIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.UUID userId = 1;</code>
     */
    public Builder setUserId(grpc.UUID value) {
      if (userIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userId_ = value;
        onChanged();
      } else {
        userIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.UUID userId = 1;</code>
     */
    public Builder setUserId(
        grpc.UUID.Builder builderForValue) {
      if (userIdBuilder_ == null) {
        userId_ = builderForValue.build();
        onChanged();
      } else {
        userIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.UUID userId = 1;</code>
     */
    public Builder mergeUserId(grpc.UUID value) {
      if (userIdBuilder_ == null) {
        if (userId_ != null) {
          userId_ =
            grpc.UUID.newBuilder(userId_).mergeFrom(value).buildPartial();
        } else {
          userId_ = value;
        }
        onChanged();
      } else {
        userIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.UUID userId = 1;</code>
     */
    public Builder clearUserId() {
      if (userIdBuilder_ == null) {
        userId_ = null;
        onChanged();
      } else {
        userId_ = null;
        userIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.UUID userId = 1;</code>
     */
    public grpc.UUID.Builder getUserIdBuilder() {
      
      onChanged();
      return getUserIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.UUID userId = 1;</code>
     */
    public grpc.UUIDOrBuilder getUserIdOrBuilder() {
      if (userIdBuilder_ != null) {
        return userIdBuilder_.getMessageOrBuilder();
      } else {
        return userId_ == null ?
            grpc.UUID.getDefaultInstance() : userId_;
      }
    }
    /**
     * <code>.UUID userId = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.UUID, grpc.UUID.Builder, grpc.UUIDOrBuilder> 
        getUserIdFieldBuilder() {
      if (userIdBuilder_ == null) {
        userIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.UUID, grpc.UUID.Builder, grpc.UUIDOrBuilder>(
                getUserId(),
                getParentForChildren(),
                isClean());
        userId_ = null;
      }
      return userIdBuilder_;
    }

    private grpc.BDecimal amount_;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.BDecimal, grpc.BDecimal.Builder, grpc.BDecimalOrBuilder> amountBuilder_;
    /**
     * <code>.BDecimal amount = 2;</code>
     * @return Whether the amount field is set.
     */
    public boolean hasAmount() {
      return amountBuilder_ != null || amount_ != null;
    }
    /**
     * <code>.BDecimal amount = 2;</code>
     * @return The amount.
     */
    public grpc.BDecimal getAmount() {
      if (amountBuilder_ == null) {
        return amount_ == null ? grpc.BDecimal.getDefaultInstance() : amount_;
      } else {
        return amountBuilder_.getMessage();
      }
    }
    /**
     * <code>.BDecimal amount = 2;</code>
     */
    public Builder setAmount(grpc.BDecimal value) {
      if (amountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        amount_ = value;
        onChanged();
      } else {
        amountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.BDecimal amount = 2;</code>
     */
    public Builder setAmount(
        grpc.BDecimal.Builder builderForValue) {
      if (amountBuilder_ == null) {
        amount_ = builderForValue.build();
        onChanged();
      } else {
        amountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.BDecimal amount = 2;</code>
     */
    public Builder mergeAmount(grpc.BDecimal value) {
      if (amountBuilder_ == null) {
        if (amount_ != null) {
          amount_ =
            grpc.BDecimal.newBuilder(amount_).mergeFrom(value).buildPartial();
        } else {
          amount_ = value;
        }
        onChanged();
      } else {
        amountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.BDecimal amount = 2;</code>
     */
    public Builder clearAmount() {
      if (amountBuilder_ == null) {
        amount_ = null;
        onChanged();
      } else {
        amount_ = null;
        amountBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.BDecimal amount = 2;</code>
     */
    public grpc.BDecimal.Builder getAmountBuilder() {
      
      onChanged();
      return getAmountFieldBuilder().getBuilder();
    }
    /**
     * <code>.BDecimal amount = 2;</code>
     */
    public grpc.BDecimalOrBuilder getAmountOrBuilder() {
      if (amountBuilder_ != null) {
        return amountBuilder_.getMessageOrBuilder();
      } else {
        return amount_ == null ?
            grpc.BDecimal.getDefaultInstance() : amount_;
      }
    }
    /**
     * <code>.BDecimal amount = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.BDecimal, grpc.BDecimal.Builder, grpc.BDecimalOrBuilder> 
        getAmountFieldBuilder() {
      if (amountBuilder_ == null) {
        amountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.BDecimal, grpc.BDecimal.Builder, grpc.BDecimalOrBuilder>(
                getAmount(),
                getParentForChildren(),
                isClean());
        amount_ = null;
      }
      return amountBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CashFlow)
  }

  // @@protoc_insertion_point(class_scope:CashFlow)
  private static final grpc.CashFlow DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.CashFlow();
  }

  public static grpc.CashFlow getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CashFlow>
      PARSER = new com.google.protobuf.AbstractParser<CashFlow>() {
    @java.lang.Override
    public CashFlow parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CashFlow(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CashFlow> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CashFlow> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.CashFlow getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

