// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public interface CashFlowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CashFlow)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UUID userId = 1;</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>.UUID userId = 1;</code>
   * @return The userId.
   */
  grpc.UUID getUserId();
  /**
   * <code>.UUID userId = 1;</code>
   */
  grpc.UUIDOrBuilder getUserIdOrBuilder();

  /**
   * <code>.BDecimal amount = 2;</code>
   * @return Whether the amount field is set.
   */
  boolean hasAmount();
  /**
   * <code>.BDecimal amount = 2;</code>
   * @return The amount.
   */
  grpc.BDecimal getAmount();
  /**
   * <code>.BDecimal amount = 2;</code>
   */
  grpc.BDecimalOrBuilder getAmountOrBuilder();
}
