// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public interface ListOfOperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListOfOperation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Operation operation = 1;</code>
   */
  java.util.List<grpc.Operation> 
      getOperationList();
  /**
   * <code>repeated .Operation operation = 1;</code>
   */
  grpc.Operation getOperation(int index);
  /**
   * <code>repeated .Operation operation = 1;</code>
   */
  int getOperationCount();
  /**
   * <code>repeated .Operation operation = 1;</code>
   */
  java.util.List<? extends grpc.OperationOrBuilder> 
      getOperationOrBuilderList();
  /**
   * <code>repeated .Operation operation = 1;</code>
   */
  grpc.OperationOrBuilder getOperationOrBuilder(
      int index);
}
