// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public interface OperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Operation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UUID userId = 1;</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>.UUID userId = 1;</code>
   * @return The userId.
   */
  grpc.UUID getUserId();
  /**
   * <code>.UUID userId = 1;</code>
   */
  grpc.UUIDOrBuilder getUserIdOrBuilder();

  /**
   * <code>string typeOperation = 2;</code>
   * @return The typeOperation.
   */
  java.lang.String getTypeOperation();
  /**
   * <code>string typeOperation = 2;</code>
   * @return The bytes for typeOperation.
   */
  com.google.protobuf.ByteString
      getTypeOperationBytes();

  /**
   * <code>string number = 3;</code>
   * @return The number.
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 3;</code>
   * @return The bytes for number.
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>.BDecimal amount = 4;</code>
   * @return Whether the amount field is set.
   */
  boolean hasAmount();
  /**
   * <code>.BDecimal amount = 4;</code>
   * @return The amount.
   */
  grpc.BDecimal getAmount();
  /**
   * <code>.BDecimal amount = 4;</code>
   */
  grpc.BDecimalOrBuilder getAmountOrBuilder();
}
