// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public final class Payment {
  private Payment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CashFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CashFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Card_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Card_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Balance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Balance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Task_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Task_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UUID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UUID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BDecimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BDecimal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BInteger_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BInteger_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpayment.proto\"<\n\010CashFlow\022\025\n\006userId\030\001 " +
      "\001(\0132\005.UUID\022\031\n\006amount\030\002 \001(\0132\t.BDecimal\"$\n" +
      "\013APIResponse\022\025\n\006idTask\030\001 \001(\0132\005.UUID\"-\n\004C" +
      "ard\022\025\n\006userId\030\001 \001(\0132\005.UUID\022\016\n\006number\030\002 \001" +
      "(\t\"\037\n\006UserId\022\025\n\006userId\030\001 \001(\0132\005.UUID\"\030\n\006S" +
      "tatus\022\016\n\006status\030\001 \001(\t\"$\n\007Balance\022\031\n\006amou" +
      "nt\030\001 \001(\0132\t.BDecimal\";\n\004Task\022\025\n\006userId\030\001 " +
      "\001(\0132\005.UUID\022\014\n\004type\030\002 \001(\005\022\016\n\006update\030\003 \001(\t" +
      "\"\025\n\004UUID\022\r\n\005value\030\001 \001(\t\"5\n\010BDecimal\022\r\n\005s" +
      "cale\030\001 \001(\005\022\032\n\007int_val\030\002 \001(\0132\t.BInteger\"\031" +
      "\n\010BInteger\022\r\n\005value\030\001 \001(\0142\321\001\n\016PaymentSer" +
      "vice\022\"\n\007payment\022\t.CashFlow\032\014.APIResponse" +
      "\022\034\n\006enroll\022\t.CashFlow\032\007.Status\022!\n\006refund" +
      "\022\t.CashFlow\032\014.APIResponse\022\036\n\007addCard\022\005.C" +
      "ard\032\014.APIResponse\022\031\n\007delCard\022\005.Card\032\007.St" +
      "atus\022\037\n\ngetBalance\022\007.UserId\032\010.BalanceB\010\n" +
      "\004grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CashFlow_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CashFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CashFlow_descriptor,
        new java.lang.String[] { "UserId", "Amount", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "IdTask", });
    internal_static_Card_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Card_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Card_descriptor,
        new java.lang.String[] { "UserId", "Number", });
    internal_static_UserId_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UserId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserId_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_Status_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Status_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_Balance_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Balance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Balance_descriptor,
        new java.lang.String[] { "Amount", });
    internal_static_Task_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Task_descriptor,
        new java.lang.String[] { "UserId", "Type", "Update", });
    internal_static_UUID_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_UUID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UUID_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_BDecimal_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_BDecimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BDecimal_descriptor,
        new java.lang.String[] { "Scale", "IntVal", });
    internal_static_BInteger_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_BInteger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BInteger_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
