// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public interface TaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Task)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UUID userId = 1;</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>.UUID userId = 1;</code>
   * @return The userId.
   */
  grpc.UUID getUserId();
  /**
   * <code>.UUID userId = 1;</code>
   */
  grpc.UUIDOrBuilder getUserIdOrBuilder();

  /**
   * <code>int32 type = 2;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>string update = 3;</code>
   * @return The update.
   */
  java.lang.String getUpdate();
  /**
   * <code>string update = 3;</code>
   * @return The bytes for update.
   */
  com.google.protobuf.ByteString
      getUpdateBytes();
}
