// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public interface TaskIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TaskId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UUID taskId = 1;</code>
   * @return Whether the taskId field is set.
   */
  boolean hasTaskId();
  /**
   * <code>.UUID taskId = 1;</code>
   * @return The taskId.
   */
  grpc.UUID getTaskId();
  /**
   * <code>.UUID taskId = 1;</code>
   */
  grpc.UUIDOrBuilder getTaskIdOrBuilder();
}
