// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public interface UserIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UUID userId = 1;</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>.UUID userId = 1;</code>
   * @return The userId.
   */
  grpc.UUID getUserId();
  /**
   * <code>.UUID userId = 1;</code>
   */
  grpc.UUIDOrBuilder getUserIdOrBuilder();
}
