// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package grpc;

public interface WhoAreYouParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WhoAreYouParams)
    com.google.protobuf.MessageOrBuilder {
}
